import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/header";
import { Roboto, Roboto_Slab } from "next/font/google";
import { cn } from "@/lib/utils";
import { Toaster } from "@/components/ui/sonner";

const fontHeading = Roboto_Slab({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-heading",
  weight: "400",
});

const fontBody = Roboto({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-body",
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cn("antialiased", fontHeading.variable, fontBody.variable)}
      >
        <div className="flex flex-col h-screen w-screen overflow-hidden">
          <Header />
          {children}
          <Toaster position="bottom-right" />
        </div>
      </body>
    </html>
  );
}
